# Generated by Django 4.2.6 on 2023-10-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscleName', models.CharField(max_length=20, verbose_name='Muscle Name')),
            ],
        ),
    ]
