# Generated by Django 4.2.6 on 2023-10-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muscle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclemodel',
            name='muscleName',
            field=models.CharField(max_length=20, unique=True, verbose_name='Muscle Name'),
        ),
    ]
