# Generated by Django 4.2.6 on 2023-10-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_usermodel_password_alter_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Refresh Token'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Password'),
        ),
    ]
