# Generated by Django 4.2.6 on 2023-10-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('desc', models.CharField(max_length=500, unique=True, verbose_name='Description')),
                ('muscleName', models.CharField(max_length=20, verbose_name='Muscle Name')),
            ],
        ),
    ]
