# Generated by Django 4.2.6 on 2023-10-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Muscle', '0002_alter_musclemodel_musclename'),
        ('Exercice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicemodel',
            name='muscleName',
        ),
        migrations.AddField(
            model_name='exercicemodel',
            name='idMuscle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Muscle.musclemodel'),
            preserve_default=False,
        ),
    ]
