# Generated by Django 4.2.6 on 2023-10-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default=-2016, max_length=20, unique=True, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userName',
            field=models.CharField(max_length=20, unique=True, verbose_name='User Name'),
        ),
    ]
